### ISSUE TITLE
Does this work with Marlin 2.0.x bug fix branch

### ISSUE THREAD

**Issue by ipatch** [juliandroid/DWIN_CR_10s_Pro#2]
Hello 👋

Discovered this repo from digging through the github issues for the InsanityAutomation of the Marlin fork.  That said, I recently purchased a SKR v1.3 logic board for my CR-10S Pro, and I'd really like to use the stock LCD that came with the printer.

I tried using the screen files provided by InsanityAutomation from the 2.0DWin branch, for the Pro printer, but the screen does not get past the boot screen for the printer.

Have you experimented with getting these files working with a Marlin 2.0 branch?

Awesome repo BTW, tons of goodies within this repo, and thanks for making it public.

cheers 🍩
Chris

**Comment by juliandroid** [comment]
Each board have specific configuration and if both boards are not pin-to-pin compatible then you cannot use directly the 2.0DWin branch since that branch is crafted to be compatible with the stock board.

Since the SKR is an ARM based board and I think it is officially supported in Marlin and assuming that it has similar capabilities then the DWIN specific cpp/h files must be refactored and properly configured, so the communication between the board and the DWIN display works. The DWIN uses serial communication with the motherboard and exchange data in both directions, so that thing is crucial to be done. From hardware point of view you need to ensure that the communication is even possible (compatible 5V/3.3V levels - atmega is 5v MCU, while arm typically is only 3.3V and I have no idea whether the SKR board is 5V compatible).

Unfortunatelly I haven't dive in the Marlin and I have no experience to help you.
InsanityAutomation is the right guy that has the knowledge and experience to help you started, assuming he has time and you can do the heavy lifting with porting/configuring.

Marlin/src/lcd/extensible_ui/lib/Creality_DWIN.cpp and Creality_DWIN.h are the main files that handle the DWIN display.
